### ISSUE TITLE
Warning C4355: 'this' used in base member initializer list

### ISSUE THREAD

**Issue by SimonEbner** [boostorg/beast#1005]
### Version of Beast
144

### All relevant compiler information
MSVC 15.5.6

I am getting the warning C4355: 'this' used in base member initializer list in file https://github.com/boostorg/beast/blob/d52e8290453fe445c8700b4819fe8e4f45633a02/include/boost/beast/core/detail/static_ostream.hpp#L125

It seems like a legit use to me and msvc being overly cautious. I am curious what is the official policy in these cases, Ignoring / muting in boost / muting outside boost?

**Comment by vinniefalco** [comment]
Weird because I don't see that warning, and it would bug me if I did since I use MSVC day to day. I prefer to fix them, and to do so without resorting to compiler switches. Sometimes that requires a creative solution.

**Comment by SimonEbner** [comment]
The issue popped up for me since updating to 14.12.25810 toolchain afaik

**Comment by vinniefalco** [comment]
There's nothing I can do about this, since it doesn't happen in the latest toolchain (15.5.5) and there's really no workaround that I can think of, unless you can come up with one? I prefer not to squelch the warning in the library. It is difficult to do anyway without affecting the user's translation units.

**Comment by SimonEbner** [comment]
Okay, many thanks for your feedback.
