### ISSUE TITLE
async_read requires lvalue reference for buffer

### ISSUE THREAD

**Issue by ricejasonf** [boostorg/beast#1112]
Is there a reason `async_read` requires an lvalue reference of a DynamicBuffer?

It is inconsistent with the interface in Asio.

Here is a minimal use case to justify allowing reference wrapped objects:

```cpp
#include <boost/asio.hpp>
#include <boost/beast.hpp>
#include <string>

int main() {
    namespace asio  = boost::asio;
    namespace beast = boost::beast;
    using asio::ip::tcp;

    asio::io_service io;
    beast::websocket::stream<tcp::socket> socket(io);
    std::string buffer{};

    socket.async_read(
        asio::dynamic_buffer(buffer),
        [](auto) { }
    );

    io.run();
}
```

I also found this, but it didn't really address the issue: https://github.com/boostorg/beast/issues/1104

If it isn't by design, I could take a whack at it but not until after C++Now.

Thank you for your consideration.

**Comment by ricejasonf** [comment]
The only purpose of `asio::dynamic_string_buffer` is to reference wrap a string as a DynamicBuffer.

As a workaround it would be better to make an equivalent wrapper that owns the object and bypass the reference wrapper altogether. (I'd rather it support both which I think would be trivial to implement)

I don't understand the Net-TS's need for the buffer to be MoveConstructible, but for your nonmovable buffers, you could use a reference wrapper similar to the one I am trying to use.

**Comment by ricejasonf** [comment]
Here is my lame workaround for the time being. :sweat_smile: 
https://github.com/ricejasonf/cppnow18_full_duplex/blob/master/include/beast_ws.hpp#L88

**Comment by vinniefalco** [comment]
>I don't understand the Net-TS's need for the buffer to be MoveConstructible

The move construction requirement is so that stream algorithms like `boost::asio::async_read_until` can take ownership of the dynamic buffer, as this implementation illustrates:
https://github.com/boostorg/asio/blob/fbe86d86b1ac53e40444e5af03ca4a6c74c33bda/include/boost/asio/impl/read_until.hpp#L55

> Here is my lame workaround for the time being.

An alternative is to use a `beast::flat_buffer` and then just construct a `string_view` out of it:

```
boost::beast::flat_buffer b;
ws.read(b);
std::string_view s{
    boost::beast::buffers_front(b.data()).data(),
    boost::beast::buffers_front(b.data()).size()};
```

**Comment by vinniefalco** [comment]
>I'd rather it support both which I think would be trivial to implement

It might be trivial to implement but it is far from trivial to document and explain to users. We would need two different concepts: **LValue DynamicBuffer** and **RValue DynamicBuffer** (names are for illustration only). This would likely cause endless confusion.

**Comment by vinniefalco** [comment]
I have identified more design problems with the Net.TS specification of DynamicBuffer. Specifically that algorithms which accept dynamic buffer parameters cannot be composed without performance penalties. I am exploring solutions.

**Comment by ricejasonf** [comment]
Are you saying that the performance issues arise from the use of reference wrapper like objects? I would think that it would be the same as a raw lvalue reference.

**Comment by vinniefalco** [comment]
I'm saying that if `f` and `g` are asynchronous composed operations which operate on a **DynamicBuffer**, and `f` is implemented in terms of `g`, then due to the semantics of the **DynamicBuffer** concept, `f` must dynamically allocate an additional piece of memory to hold its decay-copied dynamic buffer. Consider what happens otherwise:

1. `f` makes a decay-copy of the dynamic buffer via perfect forwarding
2. `f` invokes the initiating function for `g`, passing its copy of the dynamic buffer
3. `g` mutates the dynamic buffer, and control returns to `f`
4. At this point, the dynamic buffer instance held by `f` is in the state prior to the call to `g`, which is out of sync

In order for `f` to be expressible in terms of `g`, the dynamic buffer it passes to `g` must have these properties:

* Copyable
* Reference semantics
* State shared with all copies

This suggests a class containing a `shared_ptr` equivalent, which requires a memory allocation. There is no solution to this problem which does not involve an additional allocation.

Note that if `g` is a composed operation that is itself expressed in terms of some other operation `u` which also accepts a dynamic buffer, then two memory allocations are required. Each additional layer of composition necessitates an additional memory allocation.

It is my position that the semantics of **DynamicBuffer** in networking.ts is flawed, and I will file a defect report.

**Comment by vinniefalco** [comment]
See https://rawgit.com/vinniefalco/cpp/5/n4695_issue_5.html

**Comment by ricejasonf** [comment]
The problem with restricting the interface to using lvalue reference types only is demonstrated in my original minimal use case. Container types that do not satisfy `DynamicBuffer` are difficult to lift without requiring ownership within a dummy wrapper.

**Comment by ricejasonf** [comment]
> This is technically not correct. dynamic_string_buffer, in addition to referencing a string, also maintains metadata about the dynamic buffer. Specifically the size_ and max_size_ data members which among other things help define the boundary between the input and output sequences.

Ahh! I guess I should have looked at it closer.

It seems wasteful to store those in cases where the user does not specify a maximum. It's like it's there for idiot proofing or something (or I am naive about more stuff).

**Comment by vinniefalco** [comment]
This is the thinking behind DynamicBuffer:

_"...the right approach is to decouple the backing storage from the view that determines how it is populated/drained (i.e. what Asio::DynamicBuffer represents now). In a nutshell (because there's a lot more to it than I can do justice to right now), as a user I want to keep the same storage across the lifetime of a connection, but vary how it is used: during connection establishment when the peer is untrusted, keep the maximum size small; once trust is established and exchanging larger messages, user a larger maximum; access the storage as a static buffer when forwarding data to multiple destinations. This is, I think, what some users were (implicitly) telling me for years when asking for read_until to work with std::string: it's only a DynamicBuffer when used in the context of the read_until operation; when accessing the storage from other parts of the application they need it to be something else, and they don't want to have to copy the data to get it in the form they require."_

However, it created new unanticipated problems which in my opinion are worse than the problems the original design intends to solve.

**Comment by vinniefalco** [comment]
Well there is nothing to do here but wait until the paper I have submitted winds its way through wg21 which could be a while since networking is pushed back to 2023. So I will go ahead and close this.

**Comment by ecorm** [comment]
I'm currently vexed with this problem. My library takes a `std::vector<uint8_t>` as a message receive destination that I pass on to `websocket::stream::async_read` under the hood, and I want to avoid copying, heap allocations, or exposing Boost buffer types to the user.

I can't use a bare `boost::asio::dynamic_vector_buffer` as a class member, because it's not default constructible. I can't construct it with a dummy `std::vector` either, because it is not assignable.

I could wrap the `boost::asio::dynamic_vector_buffer` in `std::optional`, but that would bump up my library's C++ requirements from C++11. `boost::optional` is not appealing either, because I would like my library to support standalone Asio when Websocket support is not needed.

I'm now left with writing my own default-constructible `std::vector<uint8_t>` wrapper which meets Beast's `DynamicBuffer` requirements. I hope this isn't too hard.

**Comment by ecorm** [comment]
I used `boost::asio::dynamic_vector_buffer` as a starter and came up with the code below. It's not clear whether Beast supports Asio's `DynamicBuffer_v2` type requirement, so I went with the v1 requirement.

```c++
template <typename TStorage>
class DynamicWebsocketBuffer
{
private:
    static constexpr auto sizeLimit_ = std::numeric_limits<std::size_t>::max();

public:
    using storage_type = TStorage;
    using const_buffers_type = boost::asio::const_buffer;
    using mutable_buffers_type = boost::asio::mutable_buffer;

    DynamicWebsocketBuffer() = default;

    DynamicWebsocketBuffer(TStorage& s, std::size_t maxSize = sizeLimit_)
        : storage_(&s),
          maxSize_(maxSize)
    {}

    std::size_t size() const noexcept
    {
        if (!storage_)
            return 0;
        return (size_ == noSize_) ? std::min(storage_->size(), max_size())
                                  : size_;
    }

    std::size_t max_size() const noexcept {return maxSize_;}

    std::size_t capacity() const noexcept
    {
        return storage_ ? std::min(storage_->capacity(), max_size()) : 0;
    }

    const_buffers_type data() const noexcept
    {
        if (storage_)
            return const_buffers_type{storage_->data(), storage_->size()};
        else
            return const_buffers_type{nullptr, 0};
    }

    mutable_buffers_type prepare(std::size_t n)
    {
        assert(storage_ != nullptr);
        auto s = size();
        auto m = max_size();
        if ((s > m) || (m - s < n))
        {
            throw std::length_error("DynamicWebsocketBuffer::prepare: "
                                    "buffer too long");
        }

        if (size_ == noSize_)
            size_ = storage_->size();
        storage_->resize(s + n);
        return boost::asio::buffer(boost::asio::buffer(*storage_) + size_, n);
    }

    void commit(std::size_t n)
    {
        assert(storage_ != nullptr);
        size_ += std::min(n, storage_->size() - size_);
        storage_->resize(size_);
    }

    void consume(std::size_t n)
    {
        assert(storage_ != nullptr);
        if (size_ != noSize_)
        {
            std::size_t length = std::min(n, size_);
            storage_->erase(storage_->begin(), storage_->begin() + length);
            size_ -= length;
            return;
        }
        storage_->erase(storage_->begin(),
                        storage_->begin() + std::min(size(), n));
    }

    storage_type& storage()
    {
        assert(storage_ != nullptr);
        return *storage_;
    }

    void reset() {resetStorage(nullptr);}

    void reset(storage_type& storage, std::size_t maxSize = sizeLimit_)
    {
        resetStorage(&storage, maxSize);
    }

private:
    static constexpr auto noSize_ = std::numeric_limits<std::size_t>::max();

    void resetStorage(storage_type* storage, std::size_t maxSize)
    {
        storage_ = storage;
        size_ = noSize_;
        maxSize_ = maxSize;
    }

    TStorage* storage_ = nullptr;
    std::size_t size_ = noSize_;
    std::size_t maxSize_ = sizeLimit_;
};
```

**Comment by ecorm** [comment]
> boost::optional is not appealing either, because I would like my library to support standalone Asio when Websocket support is not needed.

I realized that Boost.Beast has a hard dependency on the rest of Boost anyway, so it ended up using a `boost::optional<boost::asio::dynamic_vector_buffer<E,A>>` class member. It can be reset to wrap a new `vector` buffer via the `emplace` method.
