### ISSUE TITLE
Compile-time error std::enable_if<! is_mutable_body_writer<Body>::value, BOOST_ASIO_INITFN_RESULT_TYPE(...)>::type is missing 

### ISSUE THREAD

**Issue by 0xdead4ead** [boostorg/beast#1252]
BOOST_BEAST_VERSION 181

There are two calls:
```cpp
template<
    class AsyncWriteStream,
    bool isRequest, class Body, class Fields,
    class WriteHandler>
typename std::enable_if<
    is_mutable_body_writer<Body>::value,
    BOOST_ASIO_INITFN_RESULT_TYPE(
        WriteHandler, void(error_code, std::size_t))>::type
async_write(
    AsyncWriteStream& stream,
    message<isRequest, Body, Fields>& msg,
    WriteHandler&& handler);
// and
template<
    class AsyncWriteStream,
    bool isRequest, class Body, class Fields,
    class WriteHandler>
typename std::enable_if<
       ! is_mutable_body_writer<Body>::value,
    BOOST_ASIO_INITFN_RESULT_TYPE(
        WriteHandler, void(error_code, std::size_t))>::type
async_write(
    AsyncWriteStream& stream,
    message<isRequest, Body, Fields> const& msg,
    WriteHandler&& handler);
```
On a second call, I get compile error, when: 
`Body = boost::beast::http::basic_file_body<boost::beast::file_posix>`
Is it the way it should be or am I not understanding something?

Here is the link!
https://github.com/0xdead4ead/beast_http_server/blob/2f6b97737869c1ca056de9a2c3f70cd9a11d12f3/include/base.hpp#L95

**Comment by vinniefalco** [comment]
What do you mean "on a second call?"

File bodies cannot be passed in const messages, because the serialization of the file changes the file's current position, which is a "logically non-const" operation. I agree this is confusing, and I will be changing it in a future version once I figure out the best way to make it work better (in the new version, messages will always be passed as const).

**Comment by 0xdead4ead** [comment]
Thanks for the support. I was too lazy to seek an answer to this question!
