### ISSUE TITLE
MSVC 2017: std::allocator<void> is deprecated in C++17 

### ISSUE THREAD

**Issue by haquocviet** [boostorg/beast#1272]
Hi,
I build a program using your library and I got so many warnings like below:

`5>  e:\vcpkg\installed\x64-windows\include\boost\beast\http\impl\write.ipp(360): warning C4996: 'std::allocator<void>': warning STL4009: std::allocator<void> is deprecated in C++17. You can define _SILENCE_CXX17_ALLOCATOR_VOID_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning. `

Of course, those warning shall be disappeared if I define suggested things. This is not a bug, however, I think you should consider any better replacement of std::allocator<void> to conform to C++17.

MSVC 2017 15.8.6 with /std:c++17 enabled
BOOST_BEAST_VERSION 181

**Comment by eido79** [comment]
Isn't this the same of #1225?

**Comment by vinniefalco** [comment]
This incorrect behavior in MSVC, see: https://github.com/chriskohlhoff/asio/issues/290#issuecomment-371867040

**Comment by haquocviet** [comment]
I am not sure if MS is aware this confusion but IMHO I think they have a reason to mark std::allocator<> deprecated.
Please look at this:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0174r0#2.4

Anyway currently this warning is not a big deal (at least for me).

**Comment by vinniefalco** [comment]
Networking TS defines a "ProtoAllocator" which is essentially `allocator<void>`. All you can really do with such an allocator is rebind it to get a "real" allocator. I think this is a good change, because it stops forcing authors from having to pick an arbitrary type to parameterize their allocator (e.g. `allocator<char>`) for the case where the actual desired type is an implementation detail or otherwise not public.

**Comment by vinniefalco** [comment]
Peter is right, the warning is spurious.

**Comment by vinniefalco** [comment]
I have modified the build scripts to squelch this warning in msvc.
