### ISSUE TITLE
How do you add a custom parameter to a request?

### ISSUE THREAD

**Issue by JanVerschaeren** [boostorg/beast#1307]
Hi,

How do you add a parameter to a request?
I am using java (spring) for the server side. And this server requests parameter named "path".
I created a request called req then i tried this: `req.insert("path", "path/to/file");`.
But the server still complains that it doesn't find a parameter called "path".

**Comment by JanVerschaeren** [comment]
I needed an URI parameter apparently, thanks for the quick response! :)

**Comment by pravic** [comment]
> URI parameters go at the end of the target string

I wish there was a more convenient way to do this (`boost::uri`? `boost::beast::uri`?).

**Comment by vinniefalco** [comment]
> I wish there was a more convenient way to do this (boost::uri? boost::beast::uri?).

Me too! I will get around to adding `beast::uri` eventually...

**Comment by neel** [comment]
Any updates on this issue ?

**Comment by madmongo1** [comment]
Hi @neel Vinnie is working on the boost.url library as we speak. It will be released as a separate library rather than part of boost.beast.

In the meantime, there are a number of uri-parsing libraries out there.

One I have used in the past is the c library uriparser: 

https://github.com/uriparser/uriparser

You can track the progress of boost.url here:

https://github.com/vinniefalco/url
