### ISSUE TITLE
consider an async_when_all, async_when_any

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1366]
This could be interesting to implement and might help with timers

**Comment by vinniefalco** [comment]
```
auto future1 = async_something(..., beast::async_future(my_strand));
```
Is the asynchronous operation launched immediately or is it launched when awaited (e.g. via `async_await_any` in your example)?

**Comment by madmongo1** [comment]
Thinking off the top of my head, it would be analagous to any existing async operation who's handler is bound to a (possibly different) executor.

It starts immediately. It is the completion handler who's invokation is controlled by:
a) the io object's executor
b) the executor bound to the handler

In terms of implementation I am thinking that the async_future would be implemented in terms of a composed operation bound to my_strand. This gives it an opportunity to prevent the final handler from "happening" in when there is a crossing case (in the case of async_await_one)

**Comment by vinniefalco** [comment]
> In terms of implementation I am thinking that the async_future would be implemented in terms of a composed operation bound to my_strand

Ah, that would work. However...

> It wouldn't be a real future as there would be no need for locking

...a strand comes with a mutex to synchronize its queue of handlers, something to keep in mind.

**Comment by madmongo1** [comment]
>  ...a strand comes with a mutex to synchronize its queue of handlers, something to keep in mind.

This is completely understood. What I mean to say is that any serialisation of access should ideally be taken care of by the executor. The reason here is that currently asio IO_contexts can be set for optimal performance when used in io_context-per-thread mode. It would be a shame to pessimise the await-multiple-things implementation with un-necessary locks.
Having said this, I can imagine a trait, or perhaps auto-selection baased on the current mode of the io_context/executor.

**Comment by vinniefalco** [comment]
I just don't see how to implement this in a general way that has a clean interface. My prototypes all end up looking like war casualties and not something that I want to put into a public interface.
