### ISSUE TITLE
Should new boost::asio::ssl::context and boost::asio::io_service be created for every http request I make in a multithreaded application while executing parallely?

### ISSUE THREAD

**Issue by opengpu** [boostorg/beast#1600]
Should new boost::asio::io_context be created for every http request?
what is the best way to deal with io_context & call io_conxt.run()

**Comment by stenreijers** [comment]
By default the io_context stops running when there are no more tasks queued to be executed after the run() call. Depending on your application design you can keep the io_context alive even when there is no more work by using boost::asio::executor_work_guard. You can keep posting work to the context and it gets executed.

Example
``` 
boost::asio::io_context ioc;
boost::asio::executor_work_guard<boost::asio::io_context::executor_type> guard(boost::asio::make_work_guard(ioc));

// Runs the context
ioc.run();

// You can keep posting work here
```

**Comment by djarek** [comment]
It's best to reuse contexts, because they may contain state that's fairly expensive to construct (and destroy).

**Comment by opengpu** [comment]
thank you.
but eg. @async http demo, 
how to reuse it...
as in Client, user log in, and then do nothing. except when user click button, a http msg is sent to Server.
it seems hard to reuse, bcause http is short connection and will close each time message is sent.

**Comment by reapler** [comment]
I use myself a solution to async_read in a loop, so it will listen to the server & keep the client alive (also useful for a broadcast facility). However i use websocket, but it should also work with http.
To send something on demand to the server from another thread, you could use [post](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/post.html) to queue work in the executor in order to async_write a message.
A complete example can be found [here](https://www.boost.org/doc/libs/1_70_0/libs/beast/example/websocket/server/chat-multi/).

**Comment by opengpu** [comment]
@reapler thanks. what situation is the best senario to use websocket?

**Comment by reapler** [comment]
Well, the Websocket protocol offers a full-duplex communication. This means the client AND the server can receive & send messages after the established Websocket handshake.
This is useful for example if you are going to broadcast a message to clients.
I can imagine that it is useful for chat or game servers.
For a better consideration between Http, Websocket or tcp socket i would view these [answers](https://stackoverflow.com/questions/14703627/websockets-protocol-vs-http).
