### ISSUE TITLE
Explore async_compose in the implementation of composed operations

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1773]
It might be useful to rewrite some of the composed operations in terms of `async_compose`. We should do one of them to compare the differences. If anything, it will help take advantage of upstream asio changes such as the nested executor_type on the initiation object.

**Comment by madmongo1** [comment]
Conclusions so far:

- Simple composed operations where there is no more than one outstanding async operation at any one time are more easily expressed using async_compose because:
  - no requirement for async_initiate boilerplate which adds zero value to the program
  - associated executor, allocator and work guards are handled automatically

- Composed operations that need to allocate memory from the associated allocator would benefit
  from a subset of stable_async_base to aid with automatic memory deallocation

- Composed operations that manage more than one simultaneous async operation are less suitable
  as they require the composed_op to fork, which involves writing a new type in any case.

**Comment by klemens-morgenstern** [comment]
Gentlemen, I usually would ask if this is still pending, but since `async_compose` is used the code-base by now, I thinkg this is resolved..
