### ISSUE TITLE
Documentation is unclear on how to cancel a websocket handshake

### ISSUE THREAD

**Issue by madmongo1** [boostorg/beast#1986]
Given:

`ws` is an object of a type which is a specialisation of `boost::beast::websocket::stream<>`

Scenario:

`ws.async_handshake(...)` is in progress.

and 

Client program wishes to terminate while being a good citizen.

Should the client program:

a) simply `cancel()` the underlying socket and exit?
b) wait for the `async_handshake` to complete, remembering the intent to close the connection and then issue `ws.async_close()`?
c) issue `ws.async_close()` during the handshake?

**Comment by vinniefalco** [comment]
The only thing you can do is cancel the underlying socket. `async_close` does not work before the handshake is complete.

**Comment by uohmak4fvpqe** [comment]
> The only thing you can do is cancel the underlying socket. `async_close` does not work before the handshake is complete.

But doing so would prevent a clean shutdown of the ssl layer, or would it ?

**Comment by ashtum** [comment]
> But doing so would prevent a clean shutdown of the ssl layer, or would it ?

Canceling the handshake operation leaves the stream in an undefined state, which is why only terminal cancellation is allowed. A clean SSL shutdown requires coordination between both sides, but that is no longer possible on this stream.

**Comment by uohmak4fvpqe** [comment]
> > But doing so would prevent a clean shutdown of the ssl layer, or would it ?
> 
> Canceling the handshake operation leaves the stream in an undefined state, which is why only terminal cancellation is allowed. A clean SSL shutdown requires coordination between both sides, but that is no longer possible on this stream.

That's what I thought.
So basically it's not possible to cancel a wss handshake at all, all we can do is close everything and instantiate another stream ?

I've been trying to find out how the appropriate sequence of asyncronous call for closing the connection on whatever state it is in, and the documentation is lacky to say the least.
here are the different cases to cover:
- the stream is connecting to tcp
  in this case, it seems to be fine just canceling the tcp layer (didn't crash at least)
- the stream is connecting to ssl
- the stream is connecting to ws

**Comment by uohmak4fvpqe** [comment]
It's a bit off the topic of this thread but I was curious to know exactly how to handle disconnection of wss stream.

there are several configurations to take care of:
- the stream is connecting to tcp : apparently it's ok to just cancel that layer
- the stream is connected to tcp : same thing
- the stream is connecting to ssl : based on my tests trying to close ssl will crash, and the assertion is clear that
I should not make a call while it's connecting, so once again we are left with cancelling the tcp layer I suppose.
- the stream is connected to ssl : now we can gracefully close the full ssl stack via the ssl layer
- the stream is connecting to wss : now we can't, again assertions fire. but now we have a ssl session open which we
can't close properly unless we wait for the outstanding wss handshake to be done.
- the stream is connected to wss : now we can close, but only when no i/o operation is outstanding, so we need to
cancel them first and then async_close the wss stack. but in practise the per-op cancellation was taking ages so the only practical way to cancel i/o was to cancel the tcp layer.

So in the end I gave up on all that undocumented complexity and I decided that just cancelling tcp was working for all cases.
I was concerned with security but it seems to be just fine since the connection is entierly dropped anyway, and obviously the applicative protocol should be designed to always await confirmation for transactions.
Am I correct ?
