### ISSUE TITLE
async_read() or async_write()

### ISSUE THREAD

**Issue by mirkub** [boostorg/beast#2133]
Hi,
I would have a general question as how to implement a http client which sends an initial request to a server and then 2 events may happen:
1) User wants to send another HTTP request (in pipeline)
or
2) Response comes from the server and client should read data from the stream.

So it's not clear whether on on_read() callback do queue.pop() which blocks until new request from user arrives or async_read() which waits until response from server comes. Any hits are appreciated.

**Comment by madmongo1** [comment]
I need to know more about your client interface in order to answer fully. It sounds as if you are writing a REST client, and you want clients of the REST client to be able to submit requests in arbitrary order and at any time, with a guarantee that the requests will be treated in the correct order.
In effect, it's an RPC client?

**Comment by mirkub** [comment]
Yes, exactly, I'd like to have a rest client which can send multiple requests without waiting for responses.
Perhaps the on_write() callback can do both: http::async_read() and http::async_write() if there are new requests in the queue?

**Comment by madmongo1** [comment]
yes, that would work. Be careful. on_write() should not launch another async_read if there is already a read in progress. It should queue the read operation, which can be dequed and initiated by in the async_read's handler.
