### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Nico946** [boostorg/beast#2228]

**Comment by madmongo1** [comment]
My first thought is that one of your completion handlers' signatures does not match.

Are you able to isolate which invocation of `bind_front_handler` is causing this?

**Comment by Nico946** [comment]
When i look at output compiler I found ``` shared_from_this()```  that cause error C2672, i don t now why

**Comment by vinniefalco** [comment]
What version of VIsual Studio?

**Comment by Nico946** [comment]
i work in Visual Studio 2017

**Comment by Nico946** [comment]
> 
> 
> Isn't that quite buggy?

That error it come from that line 
```
`  // Receive the HTTP response
    http::async_read(stream_, buffer_, res_,
      beast::bind_front_handler(
        &CRT_Reponse::on_read,
        shared_from_this()));
```

**Comment by vinniefalco** [comment]
What happens when you build it in VS2019?

**Comment by Nico946** [comment]
> 
> 
> What happens when you build it in VS2019?

No changes the same error

**Comment by madmongo1** [comment]
I think you’ll find that the error message is pointing at that line because it is the line where the entire statement ends.

the problem is that the function signature required by the async_read handler is 

void (error_code, size_t)

the function signature resulting from binding the shared pointer to the on_read function is

void (size_t)

so async_read cannot compile because the handler has the wrong signature.
