### ISSUE TITLE
Boost and ZLib vulnerabilty CVE-2018-25032

### ISSUE THREAD

**Issue by etiennearnal** [boostorg/beast#2491]
Hi Boost community,

I detected (using FNCI reports) that boost rely on ZLib 1.2.11 in `libs/beast/test` and `tools/boost_install/test`. Recently ZLib was updated to version 1.2.12 to fix a vulnerability (CVE-2018-25032), more informations in this [article](https://nakedsecurity.sophos.com/2022/03/29/zlib-data-compressor-fixes-17-year-old-security-bug-patch-errr-now/). There is any plan to use this new version ?

Thanks,

Etienne

**Comment by sehe** [comment]
Beast already updated that https://github.com/boostorg/beast/pull/2489, but it wasn't merged in time for the 1.80 release. I cannot speak for tools/boost_install (or whether that detection represents an actual dependency).

Next release will have the change.

**Comment by vinniefalco** [comment]
If you can grab the _develop_ branch of beast for now, it has the fix.

**Comment by klemens-morgenstern** [comment]
merged? can this be closed?

**Comment by vinniefalco** [comment]
Verify that the fix is in, that the CHANGELOG has it, and that the in-progress release notes for Boost has it, and then close it.

**Comment by ashtum** [comment]
Fixed in https://github.com/boostorg/beast/commit/ca824f607ccab6682b955eb91ed49753e6433069 and https://github.com/boostorg/beast/commit/925043e1e8df7474165f23c9a60223b0ab886be4.
Mentioned in the CHANGELOG: https://github.com/boostorg/beast/blob/d0dd9c50694bcbb8836775e780eb046f66b3e1d7/CHANGELOG.md?plain=1#L157
