### ISSUE TITLE
Message doc should explain how to get to basic_fields headers

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#598]
There's no explanation of `operator[]`

**Comment by ashtum** [comment]
@vinniefalco Did you mean this page: https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/ref/boost__beast__http__message.html
In Doxygen versions 1.9.0 and later, documentation for inherited members is now included in the documentation for the main type. so I guess this issue is automatically fixed.
