### ISSUE TITLE
How to get how much data already read

### ISSUE THREAD

**Issue by maytrue** [boostorg/beast#713]
I send GET request with range 

> request.set(http::field::range, range)

And I want to get how much data returns, so I try to parse response

>   http::response_parser<http::string_body> parser;
>     http::read(mSocket, readBuffer, parser, errorCode);

And print content-length with zero

> std::cout << *parser.content_length() << std::endl; 

But printing  parser.get()  got correct results.

**Comment by vinniefalco** [comment]
`content_length` only reports the value of the Content-Length field if it is present. It will return `boost::none` if the Transfer-Encoding specifies `chunked` or if the HTTP response does not have the Content-Length field present (in this case, the end of the body is signaled by connection closure).

Instead of calling `basic_parser::content_length` simply query the body container:

```
std::cout << parser.get().body.size() << std::endl;
```

Thanks

**Comment by maytrue** [comment]
OK , I got result from 

> std::cout << parser.get().payload_size()

Thanks for replay
