### ISSUE TITLE
Assertion failed: (bytes_transferred > 0)

### ISSUE THREAD

**Issue by mikea** [boostorg/beast#807]
My program often crashes with the following beast assertion:

`Assertion failed: (bytes_transferred > 0), function operator(), file xxxx/include/boost/beast/websocket/impl/read.ipp, line 436.`

### Version of Beast

120

### All relevant compiler information

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by vinniefalco** [comment]
Are you calling read with a buffer of zero bytes?

**Comment by vinniefalco** [comment]
What is your **NextLayer** type? Are you using `stream<ip::tcp::socket>`? SSL? Or something else?

**Comment by mikea** [comment]
I am using `  boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket> >`

I am always calling `_ws.async_read(` with same buffer:

```
  constexpr int READ_BUFFER_SIZE = 100000;
  boost::beast::multi_buffer _read_buffer{READ_BUFFER_SIZE};
```

and read it fully within `async_read` callback: `      _read_buffer.consume(_read_buffer.size());`

**Comment by vinniefalco** [comment]
Check it out:
https://github.com/boostorg/beast/blob/develop/include/boost/beast/websocket/impl/read.ipp#L436

The only way for `bytes_transferred==0` is for an error to occur, according to the contract for `async_read_some`:

_"Initiates an asynchronous operation to read one or more bytes of data from the stream..."_

Unless the destination buffer has zero length, which you said is not happening. And I wrote a test, the code can't get to line 436 when the buffer has zero length. I'm gonna need some help figuring this out, it could be something to do with how the OpenSSL stream works.

Is there a way to reproduce it without using OpenSSL? What version of OpenSSL are you using?

Thanks

**Comment by mikea** [comment]
@vinniefalco no, I don't have a good reproducer. I see this from time to time on our client talking to a custom ws server.

I am not sure why it comes back with `bytes_transferred == 0`. Maybe it is better not to crash but to handle it more gracefully?

**Comment by vinniefalco** [comment]
>Maybe it is better not to crash but to handle it more gracefully?

In theory that is true but the reason the assert is there in the first place is to detect when the state of the websocket stream has broken invariants. If we don't know what is causing the broken invariants then we cannot gracefully handle the case.

**Comment by vinniefalco** [comment]
Try adding this assert before line 431 (the `BOOST_ASIO_CORO_YIELD`)
```
BOOST_ASSERT(buffer_size( buffers_prefix(clamp(ws_.rd_remain_), cb_) > 0);
```

**Comment by mikea** [comment]
@vinniefalco then passing error to the user is a better solution than crashing.

**Comment by vinniefalco** [comment]
>passing error to the user is a better solution than crashing.

Hmm, no that's not true. Error codes are not used to signal broken invariants. And production code is not responsible for checking invariants - that's the responsibility of 1. the calling code and 2. the library author (to make sure that invariants are not broken). The asserts are there to inform the library author that something is wrong. We have to find out *why* the assert is happening, otherwise it cannot be fixed in a way that guarantees defined behavior.

**Comment by vinniefalco** [comment]
Please try this branch: https://github.com/vinniefalco/beast/commits/v122

**Comment by vinniefalco** [comment]
>What version of OpenSSL are you using?

**Comment by mikea** [comment]
> What version of OpenSSL are you using?
 1.1.0f

**Comment by mikea** [comment]
@vinniefalco I've deployed v122 version. Will report back soon.

**Comment by mikea** [comment]
@vinniefalco I still get the same error with 122 version:

Assertion failed: (bytes_transferred > 0), function operator(), file boost/beast/websocket/impl/read.ipp, line 438.

**Comment by vinniefalco** [comment]
hmm...this is very suspicious because according to the assert, the Asio implementation is breaking the invariant. According to the asio docs, `async_read_some` returns either when it has placed one or more bytes in the buffer, or when an error occurs. This assert implies that no bytes were transferred. But the condition `ws_.check_ok(ec)` is clearly `true` or else we would have not reached that line. The only explanation is that the invariant is being broken.

The only possibilities for broken invariants in this case are:

1. A bug in your version of OpenSSL
2. A bug in the implementation of `ssl::stream` (what version of Asio are you on?)
3. A bug in the networking driver
4. You are using your own AsyncStream which breaks one or more invariants

**Comment by mikea** [comment]
made sure I am up-to-date everywhere I can: 
- Openssl 1.1.0f
- Boost 1.65.1
- Beast 123

I don't use custom AsyncStream. My code follow ssl websocket client very closely.

If the problem is in boost, maybe you can introduce invariant checking code in boost asio?
In any case, I would really love to see this handled any way, but process crash. (maybe send a special error code?)

**Comment by vinniefalco** [comment]
>If the problem is in boost, maybe you can introduce invariant checking code in boost asio?

I will open an issue now that the author is active

>I would really love to see this handled any way, but process crash. (maybe send a special error code?)

The problem is that we don't know what a return value of 0 from `ssl::stream::async_read_some` is supposed to represent. The documentation for ssl stream states:

>"This function is used to asynchronously read one or more bytes of data from the stream."
http://www.boost.org/doc/libs/1_65_1/doc/html/boost_asio/reference/ssl__stream/async_read_some.html

If I add code to handle this in non-debug builds then it would need a test and I have no way to write that. I would be releasing code that affects all users without knowing under what conditions it will trigger. So I hope you understand why I am reluctant to do it.

I have been searching the web for some kind of knowledge or bug report explaining why ssl returns 0 bytes from a read operation but I have not yet found anything. If you can find some information, that would be very helpful.

**Comment by vinniefalco** [comment]
@mikea I believe this issue address your case: https://github.com/chriskohlhoff/asio/issues/298

**Comment by vinniefalco** [comment]
See: https://github.com/boostorg/beast/issues/1373#issuecomment-448271021
