### ISSUE TITLE
beast can run on arm architecture ?

### ISSUE THREAD

**Issue by nguoithichkhampha** [boostorg/beast#841]
Hi @vinniefalco , we are planning to build a websocket server on iOS and android base on beast. So, beast can run on arm architecture ? how is performance run on mobile ?

**Comment by djarek** [comment]
@nguoithichkhampha 
I used beast on a few embedded IoT platforms (e.g ARM Cortex-A53 in RPi 3 or QCA9550 MIPS based router SoC). I can confirm it works like charm :).

**Comment by vinniefalco** [comment]
It **should** work, but note that I do not have resources for ensuring that it compiles on ARM toolchains (is there a way to set that up on Travis?)

That said, I am more than happy to accept pull requests to fix any small issues that might come up. If you want Beast to have robust support for ARM then I would suggest you subscribe to the repository and test the develop and master branches from time to time. I submit new branches as a pull request so that gives users an opportunity to check out the branch and report on it before it gets merged.

**Comment by djarek** [comment]
@vinniefalco 
At work we used openWRT's(now known as LEDE) buildroot for the toolchain, but this might be overkill for this purpose(downloads and compiles the toolchain for your own architecture). Perhaps [this](https://github.com/dockcross/dockcross) could be useful.

**Comment by vinniefalco** [comment]
Well like I said I am more than happy to accept pull requests, but configuring and using a Docker image falls way outside my area of expertise and comfort.

**Comment by nguoithichkhampha** [comment]
@djarek , great news for me.
@vinniefalco , thanks for your suggestion. I will try.

**Comment by vinniefalco** [comment]
It doesn't look like there's anything actionable here so I'll go ahead and close the issue, but feel free to re-open it or create a new issue if the need arises, thanks!

**Comment by nguoithichkhampha** [comment]
just announce I have built successful beast on iOS and Android and it run well. But need more time to test the stability.
