### ISSUE TITLE
How can you create the request body after reading the headers?

### ISSUE THREAD

**Issue by chrisics** [boostorg/beast#943]
Hello,

We are retrofitting our REST server to use beast. 
In our application we need to create the type of the body (file, string, ...) after reading the http headers.
Because some POST messages have a 50+ MB body and some only have a body of 200 bytes.

How can I do this?  
Do I need a custom parser to go with async_read_header for this?

Thanks!

**Comment by vinniefalco** [comment]
Like this? http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/more_examples/change_body_type.html

**Comment by chrisics** [comment]
Of course, I should have known it was in there...
Thanks,
Great library!

**Comment by vinniefalco** [comment]
I appreciate the kind words. Any time you need help, please do not hesitate to reach out. If you want to communicate privately, my email address is on my Github profile and at the top of each beast source file (I keep all email communications confidential unless you instruct otherwise). I can provide assistance for any beast-related aspect including design work.
