### ISSUE TITLE
Please add a pipelining client example

### ISSUE THREAD

**Issue by gjasny** [boostorg/beast#987]
Hello,

I wonder if you could provide an example client which performs [pipelining](https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.1.2.2)?

If I modify the async client, remove the `socket_.shutdown` and issue another `http::async_write` in `session::on_write` I get two `read: bad version`.

Thanks,
Gregor

**Comment by vinniefalco** [comment]
Hmm...I am reluctant to provide such an implementation. It would be difficult to test, since many HTTP servers do not handle pipelining correctly (even Firefox and Chrome have it turned off). And it would greatly complicate the examples without a corresponding benefit.

You have to wait for the first call to `async_write` to complete before you issue the second one, otherwise the behavior is undefined.

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by vinniefalco** [comment]
It looks like there is nothing more to do here so I will go ahead and close the issue. Feel free to open a new one in the future should the need arise!
